#' Visualising missing data
#'
#' Plots patient-by-predictor grid showing
#' patient/predictor pairs with vs. without
#' missing data.
#'
#' @param d0 Tibble containing preprocessed data
#'   as generated by \code{preprocess_predictors}.
#'
#' @returns {ggplot2} figure with patients on
#'   ordinate, predictors on abscissa, diveded
#'   by the aggressive MS diagnosis.
#'
#' @export
plot_missingness <- function(d0) {
  d1 <- d0 |>
    tidyr::pivot_longer(
      cols = -c(id, sex, aggressive),
      names_to = "predictor",
      values_to = "value"
    ) |>
    dplyr::mutate(miss = dplyr::if_else(
      is.na(value), TRUE, FALSE
    ))

  order_missing <- function(d, x) {
    d |>
      dplyr::group_by(.data[[x]]) |>
      dplyr::summarise(n = sum(miss), .groups = "drop") |>
      dplyr::arrange(n) |>
      dplyr::pull(1)
  }
  ord_pats <- order_missing(d1, "id")
  ord_preds <- order_missing(d1, "predictor")

  caption <- c("Predictors:", paste0(seq_along(ord_preds), " = ", ord_preds)) |>
    paste(collapse = "\n")
  cap <- cowplot::ggdraw() +
    cowplot::draw_label(
      caption,
      x = 0,
      hjust = 0,
      #vjust = -0.44,
      size = 8
    )

  p <- d1 |>
    dplyr::mutate(
      id = factor(id, levels = ord_pats, ordered = TRUE),
      predictor = factor(predictor, levels = ord_preds, labels = seq_along(ord_preds), ordered = TRUE)
    ) |>
    ggplot2::ggplot() +
    ggplot2::aes(x = predictor, y = id, fill = miss) +
    ggplot2::geom_tile() +
    ggplot2::labs(x = "Predictor", y = NULL) +
    ggplot2::scale_y_discrete(labels = NULL, breaks = NULL) +
    ggplot2::scale_fill_manual(values = c("red4", "white")) +
    ggh4x::facet_grid2(
      aggressive ~ "",
      scales = "free_y",
      space = "free_y"
    ) +
    ggplot2::theme(
      legend.position = "none"
    )

  cowplot::plot_grid(
    p,
    cap,
    ncol = 2,
    rel_widths = c(4, 1)
  )
}
